### ISSUE TITLE
Tu crains, Français beaucoup?

### ISSUE THREAD

**Issue by Silvanor42** [UseAfterFreee/WarpSpeed#6]
Que fait ce programme? Je ne comprends pas ça. S'il vous plaît faire un pack de langue française. Merci beaucoup

**Comment by HiddiH** [comment]
sacre bleu

**Comment by icheered** [comment]
baguette courgette

**Comment by HiddiH** [comment]
je suis une petit baquette

**Comment by icheered** [comment]
J'ai un baguette magique

**Comment by UseAfterFreee** [comment]
Heyy
====

**Comment by HiddiH** [comment]
**grande**

**Comment by HiddiH** [comment]
### test
